### ISSUE TITLE
angular not defined

### ISSUE THREAD

**Issue by johnryan** [ch0chi/nugs-downloader#1]
Very cool project! I'm getting:

Uncaught ReferenceError: angular is not defined
on nugs.net - is it possible they no longer use angular / can you recommend a different bookmark snippet to try?

**Comment by ch0chi** [comment]
Hey! Glad you like it!

I just tested, and can confirm that they are still using angular.

Couple of questions:

1. Are you a nugs.net subscriber? The app, unfortunately, only works for subscribers.
2. Are you pressing the bookmarklet from inside a show on play.nugs.net? The downloader only works for single shows, and doesn't work for bulk downloading shows.
3. Could give me a little more detailed explanation of what led you to see that error in the console?

**Comment by johnryan** [comment]
Ah interesting - I'm not a subscriber, I just purchased a single video recording without a subscription - the url is something like `https://www.nugs.net/on/demandware.store....` I can do a trial subscription and see if that works too

**Comment by ch0chi** [comment]
A trial should work! I'll go ahead and close this for now. If you have any other issues let me know.
